spring:
  application:
    name: JpaExampleApplication
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ultimate_db
    username: shrikant
    password: kale
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        database: postgresql
        dialect: org.hibernate.dialect.PostgreSQLDialect